// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWHmjrC6Z8SZrFGH7mGt6ZeS43duenVy0',
    appId: '1:533174179382:web:7c74769c5168ecb889aa97',
    messagingSenderId: '533174179382',
    projectId: 'inbetween-e72db',
    authDomain: 'inbetween-e72db.firebaseapp.com',
    storageBucket: 'inbetween-e72db.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkz4NmndUVnNqjpx_mB0jox8LxO2nx5QI',
    appId: '1:533174179382:android:16516b4270708dd689aa97',
    messagingSenderId: '533174179382',
    projectId: 'inbetween-e72db',
    storageBucket: 'inbetween-e72db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFoPGXdpePwnlHEYnv3BrnrXAQiydkm94',
    appId: '1:533174179382:ios:25d2aa7008be0e1b89aa97',
    messagingSenderId: '533174179382',
    projectId: 'inbetween-e72db',
    storageBucket: 'inbetween-e72db.firebasestorage.app',
    iosBundleId: 'com.example.inbetween',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFoPGXdpePwnlHEYnv3BrnrXAQiydkm94',
    appId: '1:533174179382:ios:25d2aa7008be0e1b89aa97',
    messagingSenderId: '533174179382',
    projectId: 'inbetween-e72db',
    storageBucket: 'inbetween-e72db.firebasestorage.app',
    iosBundleId: 'com.example.inbetween',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWHmjrC6Z8SZrFGH7mGt6ZeS43duenVy0',
    appId: '1:533174179382:web:a3ee6cd92130acb289aa97',
    messagingSenderId: '533174179382',
    projectId: 'inbetween-e72db',
    authDomain: 'inbetween-e72db.firebaseapp.com',
    storageBucket: 'inbetween-e72db.firebasestorage.app',
  );

}